import { NextPage } from 'next'
import Head from 'next/head'
import { PokemonsShowTime } from '../components/PokemonsShowTime'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Pokemons!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <PokemonsShowTime />
      </main>
    </>
  )
}

export default Home
